let a = first.getAttribute("class")
console.log(a)
console.log(first.hasAttribute("style"))
console.log(first.hasAttribute("class"))
// first.setAttribute("hidden", "true")
// first.removeAttribute("class")
console.log(first.attributes)
console.log(first.dataset)